name: Spring Boot Backend - Build & Docker Push

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

env:
  IMAGE_NAME: snowvita/backend-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout source
        uses: actions/checkout@v4

      # 2️⃣ Set up Java JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # 3️⃣ Build Spring Boot JAR
      - name: Build Spring Boot JAR
        run: mvn clean package -DskipTests

      # 4️⃣ Log in to Docker Hub (using secrets)
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: snowvita
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # given edit permissions

      # 5️⃣ Build Docker image
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:${{ github.sha }} -t $IMAGE_NAME:latest .

      # 6️⃣ Push Docker image
      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest
