name: Spring Boot Backend - Build & Docker Push

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

env:
  IMAGE_NAME: snowvita/backend-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout source
        uses: actions/checkout@v4

      # 2️⃣ Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      # 3️⃣ Build Spring Boot JAR (Maven)
      - name: Build with Maven
        run: mvn clean

      # 4️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.snowvita }}
          password: ${{ secrets.dckr_pat__aYTy_pL4JXZPd9N9g2Y9KjuCeo }}

      # 5️⃣ Build and tag Docker image
      - name: Build Docker image
        run: docker build -t $IMAGE_NAME:${{ github.sha }} -t $IMAGE_NAME:latest .

      # 6️⃣ Push Docker image
      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest
